---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: src/main
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: src/main/go
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: src/util/jira/runtime
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: src/util/code-analyzer
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: src/util/workflows/cd/validate-version
    schedule:
      interval: weekly
